### ISSUE TITLE
Feature Request: Enable grouping on the group Thing

### ISSUE THREAD

**Issue by pfink** [Wire82/org.openhab.binding.heos#10]
Currently, the group Thing just have a switch called "Ungroup". It would be more easy if this switch would be named "Group" and supporting both functionalities, grouping and ungrouping. ON -> GROUP, OFF -> UNGROUP. That would make it more easier to "recover" previously used groups or make it possible to circumvent dynamic grouping by just having a predefined group for the relevant use cases.

**Comment by Wire82** [comment]
Good idea. I will implement this

**Comment by Wire82** [comment]
@pfink 
I uploaded a version which supports the feature. But is has a limitation. It only works if no individual name for the group is used. This is due to the identification method which is currently used within the binding.
Do you think you can test it an give a feedback?

**Comment by pfink** [comment]
Yes, of course :) I'll tell you as soon as I had time to try it out.

**Comment by Wire82** [comment]
I think its working now and I will close that Issue
