### ISSUE TITLE
Volume channel of player does not show current state correctly

### ISSUE THREAD

**Issue by pfink** [Wire82/org.openhab.binding.heos#11]
The volume channel does currently now show the current volume (that was may set via the App or by using the buttons on the device itself), but only the last volume that was set via OpenHab.

**Comment by pfink** [comment]
Seemed to be a temporary issue, works fine now. I'll reopen if it occurs again.

**Comment by Wire82** [comment]
Hi pfink,
Thank you for checking and testing the binding. Unfortunately I hade no time to work on it during the las weeks. But I hope that I will have time over the next weeks so that I can start to close the issues. :)

**Comment by pfink** [comment]
ok, thanks :) Issues #8 and PR #13 are most urgent and very easy to resolve.
