### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by pfink** [Wire82/org.openhab.binding.heos#12]
Hi @Wire82,

I noticed that you did not choose a license for this project yet. That's why I'd like to leave you this issue as a ToDo :) If you'd like to choose an open source license, https://choosealicense.com/ could support you. Very recommendable is the [Eclipse Public License 1.0](https://choosealicense.com/licenses/epl-1.0/) which is the preferred license for the most OpenHab Add-Ons. Github has an easy-to-use feature for choosing a license for a repository which is described [here](https://help.github.com/articles/adding-a-license-to-a-repository/).

Cheers,
Patrick

**Comment by Wire82** [comment]
License  Eclipse Public License 1.0 for project added. Also a license header and author added to all classes.
