### ISSUE TITLE
Bridge Username and Password edits not saved

### ISSUE THREAD

**Issue by dlibby00** [Wire82/org.openhab.binding.heos#17]
When I first attempted to edit the Username and Password of one of my bridge devices, the results did not seem to save.

When I edited the subsequently (also including a location edit) things seemed to work as I would expect.

Edits subsequent to that seem to work even without the Location edit.

I suspect this might in fact be an issue with the Paper UI itself.

**Comment by Wire82** [comment]
I can’t reproduce that problem. Changing the password and username everytime works without an issue. 
Do you have more details?
If it is an PaperUI issue I can’t change anything at the binding.:)

**Comment by dlibby00** [comment]
Let me see if I can reproduce.

**Comment by Wire82** [comment]
Are you able to reproduce it?

**Comment by dlibby00** [comment]
I have not been able to repro.

Thanks for the effort!
