### ISSUE TITLE
Add support for album art

### ISSUE THREAD

**Issue by dlibby00** [Wire82/org.openhab.binding.heos#18]
When I control my HEOS speakers via the Denon app I can see the artwork (or station logo etc...).

We should add a channel (I think a channel is the correct term) of type Image that contains this data when available.

**Comment by Wire82** [comment]
Cover artwork is already supported. The channel ist the ImageURL channel.

**Comment by dlibby00** [comment]
OK, I saw that in the thing definition file but couldn't find in the Paper UI.

Apparently I needed the Show More button.

Sorry for the noise!

**Comment by dlibby00** [comment]
A follow up question.

Is there an OpenHab Item type that would allow me to display the contents of said URL as an image?
