### ISSUE TITLE
Wrong Heos favorites entry name when it's from Amazon Music

### ISSUE THREAD

**Issue by daftndaze** [Wire82/org.openhab.binding.heos#32]
Hello,

when I save a Amazon Music radio station as a Heos favorite I can see strings like this in Basic UI as the favorites entry name.

catalog/stations/A2WXS38LOV7JL3/eyJAY2xhc3MiOiJjb20uYW1hem9uLm11c2ljcGxheXF1ZXVlc2VydmljZS5wYWdpbmcuU3RhdGlvblBhZ2VUb2tlbiIsInF1ZXVlSWQiOiJmZDYyODJiZS1kMTZiLTQ0NzctODEyYy0wOWY1ZDk2OTIwMzAiLCJjdXN0b21lcklkIjoiQTNWMDQxOTdEVUc1UEoiLCJkZXZpY2VJZCI6IkM2NkJGNjQ3NkU4QUEyNUJEMzg1M0YxQjVDQ0IzQkI5MzVENTM4NzMiLCJkZXZpY2VUeXBlIjoiQTEzOTdWWkUwS1FUUEUiLCJtYXJrZXRwbGFjZUlkIjoiQTFQQTY3OTVVS01GUjkiLCJtdXNpY1RlcnJpdG9yeSI6IkRFIiwiY3VzdG9tZXJTdWJzY3JpcHRpb25zIjpbImphdmEudXRpbC5IYXNoU2V0IixbIkxJQlJBUlkiLCJQUklNRSIsIlNUT1JFIl1dLCJhZGRpdGlvbmFsTWV0YWRhdGEiOnsiQGNsYXNzIjoiY29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5SZWd1bGFySW1tdXRhYmxlTWFwIiwiRU5USVRZX1RZUEUiOiJTVEFUSU9OIiwiU0VMRUNURURfU0VSVklDRV9USUVSIjoiUFJJTUUiLCJRVUVVRV9TSFVGRkxFIjoiZmFsc2UiLCJRVUVVRV9TRVFVRU5DRUQiOiJmYWxzZSIsIlNFTEVDVElPTl9TT1VSQ0VfVFlQRSI6IlBSSU1FX1GUQVRJT04iLCJTRUxFQ1RJT05fU09VUkNFX1NVQlRZUEUiOiI5N2I3YzQwZi1jYmMwLTQ5MTQtOTRkZi02Njc3ZTg0NDNhYjciLCJTRUxFQ1RJT05fU09VUkNFX0lEIjoiQTJXWFMzOExPVjdKTDMiLCJTRUxFQ1RJT05fU09VUkNFX1NFU1NJT05fSUQiOiIyMmEyOWJmMC0zM2MzLTRmOGItOTJhZC01YWViMjNkYTRkMjIifSwiaW5pdGlhbElkZW50aXR5SW5mb3JtYXRpb24iOlsiY29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5SZWd1bGFySW1tdXRhYmxlTGlzdCIsW11dLCJleHBlcmllbmNlSWRlbnRpdHlJbmZvcm1hdGlvbiI6WyJjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LlJlZ3VsYXJJbW11dGFibGVMaXN0IixbXV0sImNhbGxGb3JNb3JlSW5kZXgiOjk5LCJjdXJyZW50VHJhY2tJbmRleCI6MCwidHJhY2tzIjpbImphdmEudXRpbC5BcnJheUxpc3QiLFtdXSwic3RhdGlvbkluc3RhbmNlSWQiOiIyMmEyOWJmMC0zM2MzLTRmOGItOTJhZC01YWViMjNkYTRkMjIiLCJzYW1wbGVzIjpmYWxzZX0=/#chunk, catalog/stations/A2WXS38LOV7JL3/eyJAY2xhc3MiOiJjb20uYW1hem9uLm11c2ljcGxheXF1ZXVlc2VydmljZS5wYWdpbmcuU3RhdGlvblBhZ2VUb2tlbiIsInF1ZXVlSWQiOiJmZDYyODJiZS1kMTZiLTQ0NzctODEyYy0wOWY1ZDk2OTIwJzAiLCJjdXN0b21lcklkIjoiQTNWMDQxOTdEVUc1UEoiLCJkZXZpY2VJZCI6IkM2NkJGNjQ3NkU4QUEyNUJEMzg1M0YxQjVDQ0IzQkI5MzVENTM4NzMiLCJkZXZpY2VUeXBlIjoiQTEzOTdWWkUwS1FUUEUiLCJtYXJrZXRwbGFjZUlkIjoiQTFQQTY3OTVVS01GUjkiLCJtdXNpY1RlcnJpdG9yeSI6IkRFIiwiY3VzdG9tZXJTdWJzY3JpcHRpb25zIjpbImphdmEudXRpbC5IYXNoU2V0IixbIkxJQlJBUlkiLCJQUklNRSIsIlNUT1JFIl1dLCJhZGRpdGlvbmFsTWV0YWRhdGEiOnsiQGNsYXNzIjoiY29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5SZWd1bGFySW1tdXRhYmxlTWFwIiwiRU5USVRZX1RZUEUiOiJTVEFUSU9OIiwiU0VMRUNURURfU0VSVklDRV9USUVSIjoiUFJJTUUiLCJRVUVVRV9TSFVGRkxFIjoiZmFsc2UiLCJRVUVVRV9TRVFVRU5DRUQiOiJmYWxzZSIsIlNFTEVDVElPTl9TT1VSQ0VfVFlQRSI6IlBSSU1FX1NUQVRJT04iLCJTRUxFQ1RJT05fU09VUkNFX1NVQlRZUEUiOiI5N2I3YzQwZi1jYmMwLTQ5MTQtOTRkZi02Njc3ZTg0NDNhYjciLCJTRUxFQ1RJT05fU09VUkNFX0lEIjoiQTJXWFMzOExPVjdKTDMiLCJTRUxFQ1RJT05fU09VUkNFX1NFU1NJT05fSUQiOiIyMmEyOWJmMC0zM2MzLTR1OGItOTJhZC01YWViMjNkYTRkMjIifSwiaW5pdGlhbElkZW50aXR5SW5mb3JtYXRpb24iOlsiY29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5SZWd1bGFySW1tdXRhYmxlTGlzdCIsW11dLCJleHBlcmllbmNlSWRlbnRpdHlJbmZvcm1hdGlvbiI6WyJjb20uZ29vZ2xlLmNvbW1vbi5jb2xsZWN0LlJlZ3VsYXJJbW11dGFibGVMaXN0IixbXV0sImNhbGxGb3JNb3JlSW5kZXgiOjk5LCJjdXJyZW50VHJhY2tJbmRleCI6MCwidHJhY2tzIjpbImphdmEudXRpbC5BcnJheUxpc3QiLFtdXSwic3RhdGlvbkluc3RhbmNlSWQiOiIyMmEyOWJmMC0zM2MzLgRmOGItOTJhZC01YWViMjNkYTRkMjIiLCJzYW1wbGVzIjpmYWxzZX0=/#chunk

I should see the radio station name instead.
In Android app the selection just seems not to select the right favorite entry (an empty entry with no name gets selected), but the originally chosen entry is there and named correctly. So I assume that some information in the background does not match the favorites entry display name. Some kind of (id) mapping does not work as expected!?

All other Heos favorites are from tunein and they are named correctly (in the app and Basic UI) and if I choose one of them they get selected.

openHAB 2.5.10 Release Build
Bindings are at stock version
AVR is a Marantz NR1509

Is this a bug you can fix or am I doing something wrong?

Thanks for investigation!
If you need some more information, let me know.

**Comment by pfink** [comment]
This repo is not longer active, please open your issue at https://github.com/openhab/openhab-addons

**Comment by daftndaze** [comment]
Thanks, if this was no robo! ;)
